//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : StaticData.cpp
//  @ Date : 2017/9/24
//  @ Author : 211506334xyn
//
//


#include "StaticData.h"

StaticData StaticData::sharedStaticData() {

}

void StaticData::purge() {

}

int StaticData::intValueForKey(std::string key) {

}

char StaticData::stringValueFromKey(std::string key) {

}

float StaticData::floatValueFromKey(std::string key) {

}

bool StaticData::booleanFromKey(std::string key) {

}

cocos2d::CCpoint StaticData::pointFromKey(std::string key) {

}

cocos2d::CCRect StaticData::rectFromKey(std::string key) {

}

cocos2d::CCSize StaticData::sizeFromKey(std::string key) {

}

bool StaticData::int() {

}

StaticDate::~StaticData() {
	CC_SAFE_RELEASE_NULL(_dictionary);
/*
	if(NULL != _dictionary)
	{
		_dictionary->release();
		_dictionary = NULL;
	}
*/
}

StaticData::StaticData() {

}

